#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

bazel build :scala_attr_binary
bazel build :scala_attr_library
bazel build :scala_attr_test

check_file() {
    path=$1
    files=(apis.gz classes.jar infos.gz relations.gz setup.gz stamps.gz)

    for file in "${files[@]}"; do
        if [[ -f $path/$file ]]; then
            continue
        else
            return false
        fi
    done
}

check_file $(bazel info bazel-bin)/tests/phase/zinc/scala_attr_binary
check_file $(bazel info bazel-bin)/tests/phase/zinc/scala_attr_library
check_file $(bazel info bazel-bin)/tests/phase/zinc/scala_attr_test
