#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

bazel build :binary
bazel build :library
bazel build :test

check_file() {
    path=$1
    files=(apis.gz classes.jar infos.gz relations.gz setup.gz stamps.gz)

    for file in "${files[@]}"; do
        if [[ -f $path/$file ]]; then
            continue
        else
            return 1
        fi
    done
}

check_file $(bazel info bazel-bin)/tests/zinc_output/zinc/binary
check_file $(bazel info bazel-bin)/tests/zinc_output/zinc/library
check_file $(bazel info bazel-bin)/tests/zinc_output/zinc/test
