load(
    "@phase_zinc//rules:scala.bzl",
    "zinc_scala_library",
)

zinc_scala_library(
    name = "bad_syntax",
    srcs = ["BadSyntax.scala"],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
